# Dockerfile for router with CLT

FROM alpine:3.19

# Install required packages
RUN apk update
RUN apk add libmnl-dev bison flex wget make gcc musl-dev iproute2-tc iptables --no-cache
RUN wget https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-5.17.0.tar.xz
RUN tar -Jxvf iproute2-5.17.0.tar.xz
WORKDIR /iproute2-5.17.0
RUN sed -i '/IOAM6_TRACE_DATA_SIZE_MAX 244/i \ struct { \ __be64 high, low; \ } pkt_id; \ __be64 pkt_sid;' include/uapi/linux/ioam6.h
RUN make
RUN make install
RUN apk del bison flex wget make gcc musl-dev

WORKDIR /

# Copy script to set interfaces
COPY set_interfaces.sh set_interfaces.sh

CMD ["echo", "start"]
