"""
Represent a Docker Network generated by MSTG.
"""

import ipaddress

import utils
import constants


class DockerNetwork:
    """Represent a Docker network"""

    # used to generate the ip subnets
    # start at 1 because the first network will be used for telemetry.
    network_counter = 1

    def __init__(self, begin: str, end: str):
        self.begin = begin
        self.end = end
        self.name = DockerNetwork.generate_name(begin, end)

        self.network_id = DockerNetwork.network_counter + 1
        DockerNetwork.network_counter += 1
        self.network = self.create_network()

        self.subnet = self.network.with_prefixlen
        hosts = iter(self.network.hosts())
        self.gateway = next(hosts) if utils.output_is_compose() else None
        self.begin_ip = next(hosts)
        self.end_ip = next(hosts)

    def __str__(self) -> str:
        return f"Docker network {self.name}"\
            f"- Subnet: {self.subnet}"\
            f"- Gateway: {self.gateway}"\
            f"- Begin: {self.begin} (IP: {self.begin_ip})"\
            f"- End: {self.end} (IP: {self.end_ip})"\
            f"- ID: {self.network_id}"

    def pretty(self) -> str:
        """Indented string describing the object"""
        return f"Docker network {self.name}"\
            f"\n\t- ID: {self.network_id}"\
            f"\n\t- Subnet: {self.subnet}"\
            f"\n\t- Gateway: {self.gateway}"\
            f"\n\t- Begin: {self.begin} (IP: {self.begin_ip})"\
            f"\n\t- End: {self.end} (IP: {self.end_ip})"

    def create_network(self) -> ipaddress.IPv4Network | ipaddress.IPv6Network:
        """Create a network depending on the output settings."""
        if utils.output_is_k8s() and utils.topology_is_ipv4():
            return utils.convert_net_id_to_k8s_ipv4(self.network_id)
        elif utils.output_is_k8s() and utils.topology_is_ipv6():
            return utils.convert_net_id_to_k8s_ipv6(self.network_id)
        elif utils.output_is_compose() and utils.topology_is_ipv4():
            return utils.convert_net_id_to_ip4_net(self.network_id)
        elif utils.output_is_compose() and utils.topology_is_ipv6():
            return utils.convert_net_id_to_ip6_net(self.network_id)
        else:
            raise RuntimeError("Unexpected network configuration")

    def export_compose(self, file) -> None:
        """Export the Docker network in the given docker compose file."""
        mappings = {
            "name": self.name,
            "subnet": self.subnet,
            "gateway": self.gateway
        }
        if utils.topology_is_ipv4():
            file.write(constants.NETWORK_IPV4_TEMPLATE.substitute(mappings))
        else:
            file.write(constants.NETWORK_IPV6_TEMPLATE.substitute(mappings))

    @staticmethod
    def generate_name(begin: str, end: str) -> str:
        """Generate name for Docker network shared by `begin` and `end`."""
        return constants.NETWORK_NAME.format(begin, end)
