"""
Entities generated by MSTG.
"""


class Entity:
    """Represent every entity in the architecture."""

    # used to assign a unique IOAM id to every entity
    ioam_counter = 0

    def __init__(self, name: str, kubernetes_ip):
        self.name = name
        self.ioam_id = Entity.ioam_counter + 1
        Entity.ioam_counter += 1
        self.kubernetes_ip = kubernetes_ip

        # docker networks to which the entity is attached
        self.attached_networks: list[dict] = []
        # list of names of entities on which the current one depends
        # used by docker compose to start the containers in the appropriate order
        self.depends_on: set[str] = set()
        # list of commands to execute to configure the entity
        self.commands: list[str] = []

    def __str__(self) -> str:
        return f"Entity: {self.name} - ioam_id: {self.ioam_id} "\
            f"- k8s IP: {self.kubernetes_ip} - networks: {self.attached_networks} "\
            f"- depends-on: {self.depends_on} - commands: {self.commands_to_str()}"

    def pretty(self) -> str:
        """Indented string describing the object"""
        return f"Entity: {self.name}"\
                f"\n\t\t- ioam_id: {self.ioam_id}"\
                f"\n\t\t- k8s IP: {self.kubernetes_ip}"\
                f"\n\t\t- networks: {self.attached_networks}"\
                f"\n\t\t- depends-on: {self.depends_on}"\
                f"\n\t\t- commands: {self.commands_to_str(True)}"

    def commands_to_str(self, pretty: bool = False) -> str:
        """Export all commands in a string."""
        string = ""
        for cmd in self.commands:
            if pretty:
                string += f"\n\t\t\t- {str(cmd)}"
            else:
                string += f",{str(cmd)}"

        return string

    def cmds_combined(self, k8s = False):
        """Combine all commands in a single one."""
        combined = ""
        for cmd in self.commands:
            if not k8s:
                combined += f" ({cmd}) &"
            else:
                # sleep to be sure that interfaces had time to be configured properly by meshnet cni
                combined += f" (sleep 20 && {cmd}) &"
        return combined

    def get_network_pos(self, name: str) -> int | None:
        """
        Get id of attached network with given `name`.
        If not found, return None.
        """

        for net in self.attached_networks:
            if net["name"] == name:
                return self.attached_networks.index(net)

        return None
