"""
Entities generated by MSTG.
"""

import ipaddress
from abc import ABC, abstractmethod

import utils
import network
import constants


class Entity(ABC):
    """Represent every entity in the architecture."""

    # used to assign a unique IOAM id to every entity
    ioam_counter = 0

    def __init__(self, name: str, config, kubernetes_ip):
        self.name = name
        self.ioam_id = Entity.ioam_counter + 1
        Entity.ioam_counter += 1
        self.config = config
        self.kubernetes_ip = kubernetes_ip

        # networks to which the entity is attached
        self.attached_networks: list[network.Network] = []
        # list of names of entities on which the current one depends
        # used by docker compose to start the containers in the appropriate order
        self.depends_on: set[str] = set()
        # hosts to which the entity is connected to in end-to-end connections
        # used for dns configuration
        self.extra_hosts: dict[str, ipaddress.IPv4Address | ipaddress.IPv6Address] = dict()
        # end-to-end connections
        self.e2e_conns: set[str] = set()
        # list of commands to execute to configure the entity
        self.commands: set[str] = set()

    def string(self, separator) -> str:
        """String representation of entity."""

        return f"Entity: {self.name}"\
                f"{separator}- ioam_id: {self.ioam_id}"\
                f"{separator}- k8s IP: {self.kubernetes_ip}"\
                f"{separator}- networks: {", ".join(net.name for net in self.attached_networks)}"\
                f"{separator}- e2e-connections: {self.e2e_conns}"\
                f"{separator}- depends-on: {self.depends_on}"\
                f"{separator}- extra-hosts: {self.extra_hosts}"\
                f"{separator}- commands: {" | ".join(map(str, self.commands))}"

    def __str__(self) -> str:
        return self.string(" ")

    def pretty(self) -> str:
        """Pretty string of the entity."""
        return self.string("\n\t\t")

    def add_command(self, cmd: str, background=False):
        """
        Add a single command to the entity.

        :param cmd: Command to run.
        :param background: Whether to run the command as a background process.
        """
        self.commands.add(utils.generate_command(cmd, self.name, background))

    def generate_commands_file(self) -> None:
        """Write the commands inside the commands file."""

        with open(constants.COMMANDS_FILE, "a", encoding="utf-8") as f:
            f.write(f"\n# configuring {self.name} #\n")
            for cmd in self.commands:
                f.write(f"{cmd}\n")

    def get_network_pos(self, name: str) -> int | None:
        """
        Get id of attached network with given `name`.
        If not found, return None.
        """

        return next((i for i, net in enumerate(self.attached_networks) if net.name == name), None)

    def count_l3_networks(self) -> int:
        """Count number of L3 networks to which the entity is attached."""

        return sum(1 for net in self.attached_networks if net.type == network.NetworkType.L3_NET)

    @abstractmethod
    def export_compose(self, file) -> None:
        """Export the entity in the given Docker Compose `file`."""

    @abstractmethod
    def export_k8s(self) -> None:
        """Export the entity to Kubernetes configuration files."""
