apiVersion: v1
kind: Service
metadata:
  name: jaeger-svc
spec:
  type: NodePort
  ports:
    - name: "jaeger-gui"
      port: 16686
      targetPort: 16686
      nodePort: ${nodePort}
  selector:
    name: jaeger-pod
status:
  loadBalancer: {}
