apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ioam-collector-pod
  name: ioam-collector-pod
spec:
  hostname: ioam-collector-pod
  subdomain: ioam-collector-svc
  containers:
    - env:
      - name: OTEL_EXPORTER_JAEGER_ENDPOINT
        value: "http://jaeger-pod.jaeger-svc.default.svc.cluster.local:14268/api/traces"
      image: mstg_ioam_collector
      imagePullPolicy: Never
      name: ioam-collector
      ports:
        - containerPort: 7123
          hostPort: 7123
          protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  restartPolicy: OnFailure
status: {}
