apiVersion: v1
kind: Service
metadata:
  name: ${name}
spec:
  type: NodePort
  ports:
    - name: "${port}"
      port: ${port}
      targetPort: ${port}
      nodePort: ${nodePort}
  selector:
    name: ${podName}
status:
  loadBalancer: {}
