apiVersion: v1
kind: Pod
metadata:
  labels:
    name: jaeger-pod
  name: jaeger-pod
spec:
  hostname: jaeger-pod
  subdomain: jaeger-svc
  containers:
    - env:
      - name: COLLECTOR_OTLP_ENABLED
        value: "true"
      - name: LOG_LEVEL
        value: warn
      - name: MEMORY_MAX_TRACES
        value: "100"
      - name: QUERY_MAX_CLOCK_SKEW_ADJUSTMENT
        value: 5s
      image: jaegertracing/all-in-one:1.53
      name: jaeger
      ports:
        - containerPort: 16686
          hostPort: 16686
          protocol: TCP
        - containerPort: 14268
          hostPort: 14268
          protocol: TCP
        - containerPort: 4317
          hostPort: 4317
          protocol: TCP
        - containerPort: 4318
          hostPort: 4318
          protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  restartPolicy: OnFailure
status: {}
